# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='subscribe',
            field=models.NullBooleanField(choices=[(False, '\u672a\u5b9a\u9605'), (True, '\u5df2\u8ba2\u9605')], default=False, verbose_name='\u662f\u5426\u8ba2\u9605'),
        ),
    ]
