# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0002_auto_20160121_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='morning_greeting',
            field=models.TimeField(default='08:00', null=True, verbose_name='\u65e9\u62a5\u65f6\u95f4'),
        ),
    ]
