# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0003_wechatuser_morning_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='notify_subscription',
            field=models.NullBooleanField(default=True, verbose_name='\u63d0\u9192\u88ab\u8ba2\u9605\u901a\u77e5'),
        ),
    ]
