# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-04 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0004_wechatuser_notify_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='timezone',
            field=models.CharField(default=b'Asia/Shanghai', max_length=64, verbose_name='\u9ed8\u8ba4\u65f6\u533a'),
        ),
    ]
