# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name='\u63d0\u9192\u65f6\u95f4')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='\u539f\u59cb\u63cf\u8ff0')),
                ('event', models.TextField(blank=True, default='', null=True, verbose_name='\u63d0\u9192\u4e8b\u4ef6')),
                ('media_url', models.URLField(blank=True, max_length=320, null=True, verbose_name='\u8bed\u97f3')),
                ('repeat', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u91cd\u590d')),
            ],
        ),
    ]
