# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remind',
            name='status',
        ),
        migrations.AddField(
            model_name='remind',
            name='done',
            field=models.NullBooleanField(choices=[(False, '\u672a\u53d1\u9001'), (True, '\u5df2\u53d1\u9001')], default=False, verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='remind',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
