# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remind',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelTable(
            name='remind',
            table='remind',
        ),
    ]
