# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0002_auto_20160121_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='defer',
            field=models.IntegerField(default=0, blank=True, verbose_name='\u63d0\u524d\u63d0\u9192\u5206\u949f'),
        ),
        migrations.AddField(
            model_name='remind',
            name='notify_time',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='\u63d0\u9192\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='remind',
            name='time',
            field=models.DateTimeField(db_index=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
