# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remind', '0003_remind_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done')], default='pending', max_length=10, verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='remind',
            name='subscribers',
            field=models.ManyToManyField(related_name='reminds_subscribed', to=settings.AUTH_USER_MODEL, verbose_name='\u8ba2\u9605\u8005'),
        ),
        migrations.AlterField(
            model_name='remind',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminds_created', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005'),
        ),
    ]
