# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0004_auto_20151224_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='time',
            field=models.DateTimeField(db_index=True, verbose_name='\u63d0\u9192\u65f6\u95f4'),
        ),
    ]
