# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-29 12:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0005_auto_20161229_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='repeat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=4, verbose_name='\u91cd\u590d'),
        ),
    ]
