# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0005_auto_20151230_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reminds_created', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005'),
        ),
        migrations.AlterModelTable(
            name='remind',
            table='time_remind',
        ),
    ]
