# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-13 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0006_auto_20170329_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remind',
            name='media_url',
        ),
        migrations.AddField(
            model_name='remind',
            name='media_id',
            field=models.URLField(blank=True, max_length=120, null=True, verbose_name='\u8bed\u97f3\u6d88\u606f\u5a92\u4f53id'),
        ),
    ]
