# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0006_auto_20160106_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_reminds_created', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005'),
        ),
        migrations.AlterField(
            model_name='remind',
            name='subscribers',
            field=models.ManyToManyField(related_name='time_reminds_subscribed', to=settings.AUTH_USER_MODEL, verbose_name='\u8ba2\u9605\u8005'),
        ),
    ]
