# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0007_auto_20160106_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u8bbe\u7f6e\u65f6\u95f4'),
        ),
    ]
