# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-25 13:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0008_remind_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='repeat2',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='\u91cd\u590d'),
        ),
        migrations.AlterField(
            model_name='remind',
            name='repeat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=5, verbose_name='\u91cd\u590d'),
        ),
    ]
