# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 14:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0009_auto_20160111_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remind',
            name='participants',
        ),
        migrations.AddField(
            model_name='remind',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=None, verbose_name='\u8ba2\u9605\u8005'),
        ),
        migrations.RunSQL(['CREATE INDEX ON time_remind USING GIN (participants);']),
    ]
