# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-16 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eosram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='\u65f6\u95f4')),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['time'],
                'db_table': 'eosram_price_history',
            },
        ),
        migrations.CreateModel(
            name='PricePercentageChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('done', models.BooleanField(default=False, verbose_name='\u5df2\u7ecf\u63d0\u9192\u8fc7')),
                ('threshold', models.FloatField(db_index=True)),
                ('increase', models.BooleanField(verbose_name='\u4e0a\u6da8\u8fd8\u662f\u4e0b\u8dcc')),
                ('period', models.IntegerField(db_index=True, default=60, verbose_name='\u5206\u949f')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percent_change', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'db_table': 'eosram_price_percent_change',
            },
        ),
        migrations.AlterField(
            model_name='pricethresholdchange',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricethresholdchange',
            name='threshold',
            field=models.FloatField(db_index=True),
        ),
    ]
