# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eosram', '0002_auto_20180716_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepercentagechange',
            name='threshold',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricethresholdchange',
            name='threshold',
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
