# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-17 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import eosram.models.profile


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eosram', '0003_auto_20180716_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('memo', models.CharField(default=eosram.models.profile.generate_memo, max_length=64, primary_key=True, serialize=False, verbose_name='\u5145\u503c\u7801')),
                ('recharge', models.FloatField(default=0.04, verbose_name='\u5df2\u5145\u503c\u6570\u989d')),
                ('used', models.IntegerField(default=0, verbose_name='\u5df2\u4f7f\u7528\u7684\u63d0\u9192\u6b21\u6570')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4e0a\u6b21\u66f4\u65b0\u5145\u503c\u6570\u989d\u65f6\u95f4')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eosram_profile', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'eosram_price_profile',
            },
        ),
    ]
