# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eosram', '0004_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricepercentagechange',
            options={'ordering': ['-threshold']},
        ),
        migrations.AlterModelOptions(
            name='pricethresholdchange',
            options={'ordering': ['-threshold']},
        ),
        migrations.AddField(
            model_name='profile',
            name='ref',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='\u9080\u8bf7\u8005'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reward',
            field=models.IntegerField(default=0, verbose_name='\u5956\u52b1\u6b21\u6570'),
        ),
    ]
