# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-25 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eosram', '0005_auto_20180726_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recharge',
            field=models.FloatField(default=0, verbose_name='\u5df2\u5145\u503c\u6570\u989d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reward',
            field=models.IntegerField(default=20, verbose_name='\u5956\u52b1\u6b21\u6570'),
        ),
    ]
