# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-26 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eosram', '0006_auto_20180726_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eos_account',
            field=models.CharField(max_length=32, null=True, verbose_name='EOS\u8d26\u6237'),
        ),
    ]
