# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-26 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eosram', '0008_auto_20180726_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owner_id2',
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
    ]
