# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-26 05:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eosram', '0009_profile_owner_id2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eosram_profile', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
