# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-26 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eosram', '0010_auto_20180726_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='owner_id2',
            new_name='owner_id',
        ),
    ]
