# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxhook', '0002_auto_20151218_2344'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='user',
    #         name='subscribe_time',
    #         field=models.DateTimeField(null=True, verbose_name='\u5173\u6ce8\u65f6\u95f4'),
    #     ),
    # ]
