# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxhook', '0003_auto_20151224_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribe_time',
        ),
    ]
